export enum AMIEvents {
    QueueMemberStatus = 'QueueMemberStatus',
    DeviceStateChange = 'DeviceStateChange',
    HangupRequest = 'HangupRequest',
    ExtensionStatus = 'ExtensionStatus',
    QueueStatus = 'QueueStatus',
    QueueMemberPause = 'QueueMemberPause',
    Cdr = 'Cdr',
    Hangup = 'Hangup',
    ActiveCount = 'ActiveCount',
    SoftHangupRequest = 'SoftHangupRequest',
    DialBegin = 'DialBegin',
    DialEnd = 'DialEnd',
    NewConnectedLine = 'NewConnectedLine',
    NewCallerid = 'NewCallerid',
    Newchannel = 'Newchannel',
    QueueVqCallers = 'QueueVqCallers',
    BridgeCreate = 'BridgeCreate',
    BridgeDestroy = 'BridgeDestroy',
    BridgeEnter = 'BridgeEnter',
    BridgeLeave = 'BridgeLeave',
    QueueCallerJoin = 'QueueCallerJoin',
    QueueCallerHangup = 'QueueCallerHangup',
    QueueCallerLeave = 'QueueCallerLeave',
    QueueCallerAbandon = 'QueueCallerAbandon',
    AgentConnect = 'AgentConnect',
    AgentCalled = 'AgentCalled',
    AgentComplete = 'AgentComplete',
    AgentRingNoAnswer = 'AgentRingNoAnswer',
    MusicOnHoldStart = 'MusicOnHoldStart',
    MusicOnHoldStop = 'MusicOnHoldStop',
    DTMFBegin = 'DTMFBegin',
    DTMFEnd = 'DTMFEnd',
}

export const AvailableAMIEvents: AMIEvents[] = Object.values(AMIEvents)
