export enum AMIHangupCause {
    UNALLOCATED = '1', // Unallocated (unassigned) number
    NO_ROUTE_TRANSIT_NET = '2', // No route to the specified transit network
    NO_ROUTE_DESTINATION = '3', // No route to the destination
    CHANNEL_UNACCEPTABLE = '6', // The channel is unacceptable
    CALL_AWARDED_DELIVERED = '7', // Call awarded, being delivered in an established channel
    NORMAL_CLEARING = '16', // Normal call clearing
    USER_BUSY = '17', // User busy
    NO_USER_RESPONSE = '18', // No user response
    NO_ANSWER = '19', // No answer from the user
    SUBSCRIBER_ABSENT = '20', // Subscriber absent
    CALL_REJECTED = '21', // Call rejected
    NUMBER_CHANGED = '22', // Number changed
    REDIRECTED_TO_NEW_DESTINATION = '23', // Redirected to a new destination
    USER_NOT_REGISTERED = '26', // User not registered
    NORMAL_UNSPECIFIED = '31', // Normal, unspecified
    NO_CIRCUIT_AVAILABLE = '34', // No circuit or channel available
    NETWORK_OUT_OF_ORDER = '38', // Network out of order
    TEMPORARY_FAILURE = '41', // Temporary failure
    SWITCH_CONGESTION = '42', // Switch congestion
    ACCESS_INFO_DISCARDED = '43', // Access information discarded
    REQUESTED_CHAN_UNAVAIL = '44', // Requested channel not available
    PRE_EMPTED = '45', // Call has been preempted
    FACILITY_NOT_SUBSCRIBED = '50', // Facility not subscribed
    OUTGOING_CALL_BARRED = '52', // Outgoing calls barred
    INCOMING_CALL_BARRED = '54', // Incoming calls barred
    BEARERCAPABILITY_NOTAUTH = '57', // Bearer capability not authorized
    BEARERCAPABILITY_NOTAVAIL = '58', // Bearer capability not available
    BEARERCAPABILITY_NOTIMPL = '65', // Bearer capability not implemented
    CHAN_NOT_IMPLEMENTED = '66', // Channel type not implemented
    FACILITY_NOT_IMPLEMENTED = '69', // Facility not implemented
    INVALID_CALL_REFERENCE = '81', // Invalid call reference value
    INCOMPATIBLE_DESTINATION = '88', // Incompatible destination
    INVALID_MSG_UNSPECIFIED = '95', // Invalid message, unspecified
    MANDATORY_IE_MISSING = '96', // Mandatory information element is missing
    MESSAGE_TYPE_NONEXIST = '97', // Message type nonexistent or not implemented
    WRONG_MESSAGE = '98', // Message not compatible with call state
    IE_NONEXIST = '99', // Information element nonexistent or not implemented
    INVALID_IE_CONTENTS = '100', // Invalid information element contents
    WRONG_CALL_STATE = '101', // Message not compatible with call state
    RECOVERY_ON_TIMER_EXPIRE = '102', // Recovery on timer expiry
    MANDATORY_IE_LENGTH_ERROR = '103', // Mandatory information element length error
    PROTOCOL_ERROR = '111', // Protocol error, unspecified
    INTERWORKING = '127', // Interworking, unspecified
}
